# This part is reloadable!
graphite_valid = false
graphite_host = "graphite.taiyouxi.net:2003" #for :2003 tcp of graphite
graphite_memstats = true
graphite_gcstats = true
graphite_flush_interval = 10000000000
graphite_prefix = "gamex"
