[CommonCfg]
#通用配置

#
# runmode = [dev, test, preview, prod]
# now only use for output statistic
#
run_mode="dev"

# 游戏同步服务地址 需要完整的公网地址
listen=":10012"
publicip = "10.0.1.69"
etcd_endpoint = ["http://127.0.0.1:2379/"]
# Etcd Root Path 注意以/开头 如 /a4k
etcd_root = "/a4k"

# 游戏开始通知api地址 需要内网ip
listen_notify_addr="127.0.0.1:8792"

#只有这个token和gamex发给match的一致时才能正确匹配到
#正式环境中,只有渠道配置服需要单独处理,使得可以和正式服务器能够有效隔离开
match_token="dev"

# 游戏大区ID GID
gid = "0"